openapi: 3.0.0
info:
  title: Sample Shop Api
  description: Sample shop docs with sum test docs
  version: 0.1.9
servers:
  - url: http://127.0.0.1
    description: localserver

paths:
  /search:
    get:
      description: search between products and return result
      parameters:
        - name: term
          in: query
          required: true
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: list of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  price:
                    type: integer
                  quantity:
                    type: integer
        400:
          description: when parameters is not correct
        500:
          description: internal server err
  /cart-item:
    post:
      description: add product item to cart if cart not exist create cart then insert product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartItemBody'
      responses:
        200:
          description: add item to cart successfully
        400:
          description: incorrect params
        500:
          description: internal server error

components:
  schemas:
    CartItemBody:
      type: object
      required:
        - product_id
        - quantity
        - price
      properties:
        cart_item_id:
          description: when we want update the quantity of item
          type: integer
        cart_id:
          type: integer
        product_id:
          type: integer
        quantity:
          type: integer
        price:
          type: integer